# Generated by Django 4.2.6 on 2023-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.URLField(max_length=255),
        ),
    ]
